version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: graphql
    restart: always
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=graphql
    ports:
      - "4050:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
